# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62f3872c1f9895d0cd6520e5baf5825559924d0e4561ce1c898592392fc0325f4d241f84e285c17759435e2613e3ee83802dd2566ec7938f3c3edfd39ede7ac9

test:
  secret_key_base: bead70cd141d2066585a130cd4d8fbb2b041b32dae3eac4db76dbe524cc12589271c98f2fbd44daacf1d353cf2e07d19171e157b53ac5b6d48852b071f36b25a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
